providers:
  type: Zend_Controller_Router_Route_Static
  route: /providers
  defaults:
    module: providers
    controller: index
    action: index
providersedit:
  route: /providers/management/edit/:id
  defaults:
    module: providers
    controller: management
    action: edit
