mvc:
  brands:
    index:
      index:
        allow: guest
      create:
        allow: guest
      complete:
        allow: guest
      plan-info:
        allow: guest
      complete-payment:
        allow: guest
      canceled-payment:
        allow: guest
    management:
      allow: guest
    cli:
      check-status:
        allow: guest
